### PR TITLE
Allow sys uid min/max and sys gid min/max to be configured

### PR DESCRIPTION
**Pull request by joshgarnett**
This allows the system uid/gid min/max to be configured

### CODE REVIEW

**Comment by Rockstar04** [comment]
As long as the defaults stay within the range of all of our supported platforms (ubuntu >= 12.04, debian >= 6.0, centos >= 6.4, redhat >= 6.4, oracle >= 6.4) this seems fine to me.

Out of curisoty, what is your use case for adjusting these?

**Comment by evaryont** [comment]
I'd like to see this merged in, as well. For arch, the values are set to 500/999 instead of the defaults which leaves it at 100/999.

The benefit is that the packagers can reserve uids 1-499 for a variety of uses (dbus system user, systemd-networkd's user, ntp, etc) and I can generate my own system accounts (`useradd -r`) without worry about conflicts, etc.

**Comment by joshgarnett** [comment]
My company has reserved >= 500 for user accounts due to some legacy decisions. Any system accounts that created between 500 & 1000 currently get nuked our configuration management system.

**Comment by Rockstar04** [comment]
Cool thanks for the input!

**Comment by chris-rock** [comment]
Thanks for adding this feature @joshgarnett

**Pull request merged**
