### PR TITLE
Update sysctl.rb

### PR DESCRIPTION
**Pull request by Rockstar04**
Lowercase file. Relates to #80

### CODE REVIEW

**Comment by Rockstar04** [comment]
I'll to wait until I get to work tomorrow to run the rest of the tests for this and see if it is as simple as that. (8AM CST or 1PM UTC)

**Comment by Rockstar04** [comment]
Yes, I can confirm that this will solve the issue in #80 (for at least Ubuntu 14.04, I am letting all of the kitchen tests runs now).

**Comment by chris-rock** [comment]
Thanks @Rockstar04 and @lhriley-tm

**Comment by chris-rock** [comment]
I'll do some extra tests over the weekend and bump the version afterwards. In the meantime, please go ahead and use the master

**Comment by lhriley-tm** [comment]
I just completed a kitchen build successfully against your master branch. I will consider this issue resolved once I see the version bump.

Thanks for the quick fix!

**Comment by dupuy** [comment]
@chris-rock version bump on this?

**Comment by chris-rock** [comment]
@dupuy latest master is pushed to supermarket as version 1.3.0

**Pull request merged**
