### PR TITLE
Enable pam_pwquality in rhel-family > 7

### PR DESCRIPTION
**Pull request by boldandbusted**
Howdy. Here's my pull request implementing a fix re: https://github.com/hardening-io/chef-os-hardening/issues/102

Please test, and let me know if you need more work to make this a good PR! Thanks!

Jesse

### CODE REVIEW

**Comment by boldandbusted** [comment]
Also, how do I get this fix up to the "Chef Supermarket"? :)

**Comment by boldandbusted** [comment]
Success! :)

**Comment by boldandbusted** [comment]
Howdy. Just a lonely, lonely bump. :) Let me know if you need more... or less.

**Comment by chris-rock** [comment]
awesome, thanks @boldandbusted

**Pull request merged**
